# Generated by Django 3.2.18 on 2023-04-28 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titbit', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bg_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='bg.png', max_length=255, verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='user.png', max_length=255, verbose_name='Profile Picture'),
        ),
    ]
