# Generated by Django 3.2.18 on 2023-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titbit', '0009_auto_20230502_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bg_pic',
            field=models.ImageField(blank=True, default='images/bg.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user.png', upload_to='images/'),
        ),
    ]
