# Generated by Django 3.2.18 on 2023-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titbit', '0012_auto_20230504_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
